server:
  port: 666
spring:
  redis:
    host: 39.107.248.67
    password: Dxs&***1314?!
    port: 16379

logging:
  level:
    xyz:
      dingxs:
        subscribe: debug
  file:
    path: logs
    name: logs/subscribe.log

springfox:
  documentation:
    enabled: true
    swagger-ui:
      enabled: true
      baseUrl: /sw
    openApi:
      enabled: true

subscribe:
  sniff:
    count: 10
    successCount: 8
    timeout: 1000
    task:
      cron: 0 0/1 * * * ?
  authorized:
    token: 7a9f0305db436ed82a0c91f270fd5685
  portRange:
    min: 10000
    max: 19999